package com.aiplus.backend.email.strategy;

public enum EmailType {

    // Auth & Security
    LOGIN_ALERT, PASSWORD_CHANGED, ACCOUNT_LOCKED,

    // Subscription lifecycle
    SUBSCRIPTION_CREATED, SUBSCRIPTION_CONFIRMED, SUBSCRIPTION_ACTIVATED, SUBSCRIPTION_RENEWAL_REMINDER,
    SUBSCRIPTION_RENEWED, SUBSCRIPTION_RENEWAL_FAILED, SUBSCRIPTION_CANCELED, SUBSCRIPTION_EXPIRED,
    SUBSCRIPTION_SUSPENDED,

    // Payments
    PAYMENT_SUCCESSFUL, PAYMENT_FAILED, PAYMENT_METHOD_ADDED, PAYMENT_METHOD_UPDATED, PAYMENT_METHOD_EXPIRED,
    PAYMENT_METHOD_REMOVED,

    // API usage & Keys
    API_KEY_GENERATED, API_KEY_ROTATED, API_USAGE_WARNING, API_USAGE_LIMIT_REACHED,

    // Instances lifecycle
    INSTANCE_DEPLOYED, INSTANCE_DEPLOYMENT_FAILED, INSTANCE_STARTED, INSTANCE_STOPPED, INSTANCE_DELETED, INSTANCE_ERROR,

    // Dev / Creators events
    MODEL_PUBLISHED, MODEL_UPDATED, MODEL_NEW_SUBSCRIBER, MODEL_REVIEW_RECEIVED, DATASET_PUBLISHED, DATASET_PURCHASED,
    PAYOUT_PROCESSED, PAYOUT_FAILED, MONTHLY_REVENUE_REPORT, CONTENT_FLAGGED, ACCOUNT_WARNING, ACCOUNT_SUSPENDED,

    // System events
    SYSTEM_MAINTENANCE, SYSTEM_OUTAGE, SYSTEM_RESTORED, NEW_FEATURE_ANNOUNCEMENT, PLATFORM_UPDATE, SECURITY_ALERT,
    TERMS_UPDATED, PRIVACY_POLICY_UPDATED,

    // Generic / Marketing
    WELCOME_EMAIL, BROADCAST_MESSAGE,

    // Existing
    PASSWORD_RESET, ACCOUNT_ACTIVATION, CONTACT_MESSAGE
}
